# LambdaTest Configuration

# Project and folder configuration
project_id: "01KNKDXPYMKJX60FR9Q44C64WG"
folder_id: "01KNKDXR8VYZT98WG1TEX99AZC"

# Test Run configuration
assignee: 1000383103
environment_id: 1

# Test URL for automation - modified on head branch to verify config is read from PR source branch
test_url: "https://stage-demo.lambdatestinternal.com"
